config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  
  resources :users
  resources :questions
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  post 'comments/:id' => 'comments#create' ,as: :comments
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :commenters, through: :comments, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :questions
    has_many :comments, dependent: :destroy
    has_many :comment_questions, through: :comments, 
    source: :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        user = User.find(session[:user_id])
        question = Question.find(params[:id])
        comment = user.comments.build(question_id: question.id)
        comment.content = params[:comment][:content]
        comment.save
        redirect_to question_path(question.id)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def new
        @question = Question.new
    end
    
    def create
        user = User.find_by(id: session[:user_id])
        question = user.questions.build(question_params)
        question.save
        redirect_to questions_path
    end
    
    def index
        @questions = Question.all
    end
    
    def show
        @question = Question.find(params[:id])
        @comment = Comment.new
        @comments = @question.comments
    end
    
    private
    def question_params
        params.require(:question).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(email: params[:session][:email])
        session[:user_id] = user.id
        redirect_to root_path
    end
    
    def destroy
        session.delete(:user_id)
        redirect_to root_path
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def top
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
    @users = User.all
end

def show
    @user = User.find(params[:id])
    @questions = @user.questions
end

def new
    @user = User.new
end

def create
    user = User.new(user_params)
    user.save
    redirect_to users_path
end
def edit
    @user = User.find(params[:id])
end

def update
    user = User.find(params[:id])
    user.update_attributes(user_params)
    redirect_to user_path
end

def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
end
private
    def user_params
        params.require(:user).permit(:name,
        :email, :profile)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HiveApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'トップ', root_path %>
<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<h1>質問一覧</h1>
<ul>
    <% @questions.each do |question| %>
    <li>
        <%= link_to question.title, question_path(question.id) %> | <%= question.content %> |
        by <% user = User.find(question.user.id) %><%= link_to question.user.name, user %>さん
    </li>
    <% end %>
</ul>

app/views/questions/new.html.erb
<h1>新しい質問</h1>
<%= form_for(@question) do |f| %>
<p>タイトル</p>
<%= f.text_field :title %>
<p>内容</p>
<%= f.text_area :content %>
<p><%= f.submit '投稿' %></p>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.content %></p>

<h2>コメントをする</h2>
<%= form_for(@comment) do |f| %>
<%= f.text_area :content %>
<%= f.submit '投稿する' %>
<% end %>

<h3>この投稿へのコメント一覧</h3>
<ul>
    <% @comments.each do |comment| %>
    <li><%= comment.content %> by <%= comment.user.name %>さん</li>
    <% end %>
</ul>

app/views/static_pages/top.html.erb
<% if session[:user_id] %>
<h1>Hiveアプリ</h1>
<p>このアプリは、Railsを使ってWebアプリを作ることができるようになる、練習ようのアプリです。</p>
<%= link_to 'ユーザー一覧', users_path %> |
<%= link_to '質問を作る', new_question_path %> |
<%= link_to '質問一覧', questions_path %> |
<%= link_to 'ログアウト', logout_path, method: :delete %>
<% else %>
<h1>Hiveアプリにようこそ！</h1>
<%= link_to 'ログイン', login_path %> | <%= link_to '新規登録',
new_user_path %>
<% end %>

app/views/static_pages/top2.html.erb
いいいいい

app/views/static_pages/top3.html.erb
はい。工藤です。

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>
<%= form_for(@user) do |f| %>
<p>名前</p>
<%= f.text_field :name %>
<p>メールアドレス</p>
<%= f.text_field :email %>
<p>プロフィール</p>
<%= f.text_area :profile %>
<p><%= f.submit '更新' %></p>
<% end %>

app/views/users/index.html.erb
<%= link_to '新規作成', new_user_path %>
<ul>
    <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user.id) %> | <%= user.email %>
    | <%= user.profile %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>新しいユーザーの追加</h1>
<%= form_for(@user) do |f| %>
<p>名前</p>
<%= f.text_field :name %>
<p>メールアドレス</p>
<%= f.text_field :email %>
<p>プロフィール</p>
<%= f.text_area :profile %>
<p><%= f.submit '登録' %></p>
<% end %>

app/views/users/show.html.erb
<p><%= @user.name %> | <%= @user.email %> | <%= @user.profile %>
<p><%= link_to '編集', edit_user_path %> | 
<%= link_to '削除', user_path, method: :delete %></p>
<h2><%= @user.name %>さんの投稿一覧</h2>
<ul>
    <% @questions.each do |question| %>
    <li><%= link_to question.title, question %></li>
    <% end %>
</ul>